spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: suhrob
    password: 123
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
  kafka:
    bootstrap-servers: localhost:9092
server:
  port: 8083